version: "3"
services:
  nacosmysql:
    image: mysql:5.7
    container_name: naocsmysql
    restart: always
    volumes:
      - /www/wwwroot/shuishan-docker/nacos/nacos-mysql.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql
      - /www/wwwroot/shuishan-docker/nacos/mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  nacos:
    container_name: nacos-standalone
    image: nacos/nacos-server:latest
    environment:
    - MODE=standalone
    - MYSQL_SERVICE_HOST=nacosmysql
    - MYSQL_SERVICE_PORT=3306
    - MYSQL_SERVICE_USER=root
    - MYSQL_SERVICE_PASSWORD=123456
    - MYSQL_SERVICE_DB_NAME=nacos_config
    - SPRING_DATASOURCE_PLATFORM=mysql
    restart: always
    ports:
    - "8848:8848"
    - "9848:9848"
    - "9849:9849"
    depends_on:
      - nacosmysql
