apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql
  labels:
    app: nacosmysql
spec:
  ports:
    - port: 3306
  selector:
    app: nacosmysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-mysql
  labels:
    app: nacosmysql
spec:
  selector:
    matchLabels:
      app: nacosmysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nacosmysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: nacosmysql-persistent-volume
      volumes:
      - name: nacosmysql-persistent-volume
        persistentVolumeClaim:
          claimName: nacosmysql-pvc
