apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nacosmysql-pv
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs: 
    path: /nfsdata/prod-nacos-mysql
    server: xx.xx.xx.xx
