kind: PersistentVolumeClaim
apiVersion:  v1
metadata: 
  name: nacosmysql-pvc
spec: 
  accessModes: 
    - ReadWriteOnce           
  resources: 
    requests: 
      storage: 8Gi
  storageClassName: nfs
